# Generated by Django 3.1.2 on 2020-10-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
