# Generated by Django 3.1.2 on 2020-10-22 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201022_0440'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('order', 'path')},
        ),
    ]
