# Generated by Django 3.1.2 on 2020-10-24 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20201024_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='next',
        ),
    ]
