# Generated by Django 3.1.2 on 2020-10-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='tip',
            field=models.TextField(null=True),
        ),
    ]
