# Generated by Django 3.1.2 on 2020-10-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20201027_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='url_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('cypher', 'Cypher'), ('attack', 'Attack'), ('story', 'Story')], default='story', max_length=11),
        ),
    ]
