# Generated by Django 3.1.2 on 2020-10-29 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20201028_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('order', models.IntegerField()),
                ('place', models.TextField()),
                ('image', models.CharField(help_text='image name', max_length=150, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='step',
            name='story',
        ),
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('cypher', 'Cypher'), ('attack', 'Attack'), ('story', 'Story')], default='story', max_length=11),
        ),
        migrations.AddField(
            model_name='gamestep',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.story'),
        ),
    ]
