# Generated by Django 3.1.2 on 2020-11-01 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20201029_0257'),
        ('game', '0010_auto_20201029_0451'),
    ]

    operations = [
    ]
