# Generated by Django 3.1.2 on 2020-11-02 13:49

from django.db import migrations
from django.contrib.auth.models import User

def create_superuser(apps, schema_editor):
    User.objects.create_superuser(username='linglung', password='linglung')
    User.objects.create_superuser(username='liliana', password='liliana')
    User.objects.create_superuser(username='jonathan', password='jonathan')

class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_merge_20201101_2148'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
