# Generated by Django 3.1.2 on 2020-11-02 13:49

from django.db import migrations
from django.contrib.auth.models import User

def create_superuser(apps, schema_editor):
    User.objects.create_superuser(username='sigma', password='sigma123')
    User.objects.create_superuser(username='epsilon', password='epsilon123')
    User.objects.create_superuser(username='omega', password='omega123')

class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_merge_20201101_2148'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
